linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - scopelint
    - varnamelen
    - gci
  fast: true

linters-settings:
  misspell:
    ignore-words:
      - adn

issues:
  exclude-rules:
    - path: '(.+)_schema\.go'
      linters:
        - lll
        - funlen
        - maintidx
    - path: '(.+)_test\.go'
      linters:
        - funlen