# https://taskfile.dev

version: '3'


dotenv: ['.env']


vars:
  HOSTNAME: github.com
  NAMESPACE: terraform-providers
  NAME: edgecast
  BINARY: terraform-provider-{{.NAME}}
  VERSION: 1.3.3


includes:
  integration_test:
    desc: runs all integration tests
    taskfile: ./test/integration/Taskfile.yaml
    dir: ./test/integration


tasks:
  generate:
    desc: generates documentation markdown
    cmds:
      - go generate

  build:
    desc: builds terraform-provider-edgecast
    cmds:
      - go build -o {{.BINARY}}

  install:
    desc: installs the source as the specified version of the terraform provider
    cmds:
      - task: build
      - mkdir -p ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{OS}}_{{ARCH}}
      - mv {{.BINARY}} ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{OS}}_{{ARCH}}

  lint:
    desc: runs lint against go files
    cmds:
      - golangci-lint run -v

  test:
    desc: runs go test against go files
    cmds:
      - go test -v -cover ./...

  test-cover:
    desc: 'runs tests and shows coverage report'
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  default:
    cmds:
      - task: lint
      - task: test
      - task: generate
      - task: install
      - task: integration_test:default
