# https://taskfile.dev

version: '3'

dotenv: ['.env']

includes:
  test:
    taskfile: ./test/integration/Taskfile.yaml
    dir: ./test/integration


tasks:
  default:
    cmds:
      - task test:default